version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "composer"
    directory: "/modules/CRM/Mail"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "composer"
    directory: "/modules/Libs/PHPExcel"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "composer"
    directory: "/modules/Libs/TCPDF"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
