<?php

/*

+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube archive plugin                         |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Milan Kozak <hodza@hodza.net>                                 |
+-----------------------------------------------------------------------+

@version $Id: labels.inc 2993 2009-09-26 18:32:07Z alec $

*/

$labels = array();
$labels['buttontitle'] = 'Archivovat zprávu';
$labels['buttontitle_compose'] = 'Archivovat zprávu';
$labels['archived'] = 'Úspěšně vloženo do archivu';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'Epesi Archiv';
$labels['archivesentfolder'] = 'Epesi Sent Archiv';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>
