<?php

$labels = array();
$labels['buttontitle'] = 'Nachricht archivieren';
$labels['buttontitle_compose'] = 'Nachricht archivieren';
$labels['archived'] = 'Nachricht erfolgreich archiviert';
$labels['archived_duplicate'] = 'Nachricht bereits archiviert';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'EPESI Archiv';
$labels['archivesentfolder'] = 'EPESI Sent Archiv';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>