<?php

$labels = array();
$labels['buttontitle'] = 'Archive this message';
$labels['buttontitle_compose'] = 'Archive this message after sending';
$labels['archived'] = 'Successfully archived';
$labels['contactnotfound'] = 'Matching contact or company not found. Click again to force archive without contact association.';
$labels['archivefolder'] = 'Epesi Archive';
$labels['archivesentfolder'] = 'Epesi Sent Archive';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>
