<?php

$labels = array();
$labels['buttontitle'] = 'Arhiveeri see kiri';
$labels['buttontitle_compose'] = 'Arhiveeri see kiri';
$labels['archived'] = 'Edukalt arhiveeritud';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'Epesi Arhiveeri';
$labels['archivesentfolder'] = 'Epesi Sent Archiveeri';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>
