<?php

$labels = array();
$labels['buttontitle'] = 'Archiver ce message';
$labels['buttontitle_compose'] = 'Archiver ce message';
$labels['archived'] = 'Un message archivé avec succès';
$labels['archived_duplicate'] = 'Message déjà archivés';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'EPESI Archive';
$labels['archivesentfolder'] = 'EPESI Sent Archive';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>