<?php

$labels = array();
$labels['buttontitle'] = 'Przenieś do archiwum';
$labels['buttontitle_compose'] = 'Przenieś do archiwum po wysłaniu wiadomości';
$labels['archived'] = 'Pomyślnie zarchiwizowano';
$labels['contactnotfound'] = 'Nie znaleziono kontaktu ani firmy o takim adresie e-mail. Kliknij ponownie aby zarchiwizować wiadomość bez połączenia z kontaktem.';
$labels['archivefolder'] = 'Archiwum (Epesi)';
$labels['archivesentfolder'] = 'Archiwum Wysłane (Epesi)';
$labels['invalidfolder'] = 'Nie można przenieść do archiwum z tego folderu';

?>
