<?php

$labels = array();
$labels['buttontitle'] = 'Переместить выбранное в архив';
$labels['buttontitle_compose'] = 'Переместить выбранное в архив';
$labels['archived'] = 'Перенесено в Архив';
$labels['archived_duplicate'] = 'Уже в архиве';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'Архив EPESI';
$labels['archivesentfolder'] = 'Архив EPESI Sent';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>