<?php

$labels = array();
$labels['buttontitle'] = '封存此信件';
$labels['buttontitle_compose'] = '封存此信件';
$labels['archived'] = '已成功封存';
$labels['archived_duplicate'] = '已经归档';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'EPESI 封存';
$labels['archivesentfolder'] = 'EPESI Sent Archive';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>