<?php

namespace Epesi\Modules\Roundcube\Services;

use Epesi\Modules\Roundcube\Roundcube;
use RuntimeException;

/**
 * Roundcube's config/config.inc.php, generated from Laravel's own config, so
 * it can be rewritten whenever that changes (`roundcube:install
 * --configure-only`). It replaces what Epesi's hand-written RC config did at
 * runtime: same database, rc_ prefix, the epesi_* plugins.
 */
class RoundcubeConfigWriter
{
    public const PLUGINS = ['epesi_sso', 'epesi_archive', 'epesi_addressbook', 'markasjunk', 'zipdownload'];

    public function write(): string
    {
        $file = Roundcube::path('config'.DIRECTORY_SEPARATOR.'config.inc.php');

        $lines = ['<?php', '', '// Generated by `php artisan roundcube:install` from Epesi\'s configuration.', '// Changes here are overwritten; change Epesi\'s .env/config and run it again.', '', '$config = [];'];

        foreach ($this->settings() as $key => $value) {
            $lines[] = '$config['.var_export($key, true).'] = '.var_export($value, true).';';
        }

        file_put_contents($file, implode(PHP_EOL, $lines).PHP_EOL);

        return $file;
    }

    /**
     * @return array<string, mixed>
     */
    public function settings(): array
    {
        $verify = (bool) config('epesi-mail.imap_validate_cert', true);
        $tls = $verify ? null : ['ssl' => ['verify_peer' => false, 'verify_peer_name' => false]];

        return [
            'db_dsnw' => $this->dsn(),
            'db_prefix' => (string) config('epesi-roundcube.table_prefix'),

            // epesi_sso sets the real servers per account at login.
            'imap_host' => 'localhost:143',
            'imap_conn_options' => $tls,
            'smtp_conn_options' => $tls,

            'des_key' => bin2hex(substr(Roundcube::key('des'), 0, 16)),
            'cipher_method' => 'AES-256-CBC',
            'epesi_sso_key' => bin2hex(Roundcube::key('sso')),

            // The cookie reaches Laravel (EndRoundcubeSession deletes the
            // session on logout), and lasts as long as Laravel's own.
            'session_name' => Roundcube::SESSION_COOKIE,
            'session_auth_name' => 'epesi_roundcube_sessauth',
            'session_path' => Roundcube::cookiePath(),
            'session_lifetime' => (int) config('session.lifetime'),

            'plugins' => self::PLUGINS,
            'skin' => 'elastic',
            'product_name' => 'Epesi Mail',
            'support_url' => '',
            'x_frame_options' => 'sameorigin',
            'enable_installer' => false,
            'log_dir' => storage_path('logs'.DIRECTORY_SEPARATOR.'roundcube').DIRECTORY_SEPARATOR,
            'temp_dir' => storage_path('framework'.DIRECTORY_SEPARATOR.'roundcube').DIRECTORY_SEPARATOR,
        ];
    }

    /** A Laravel connection (the default one unless named) as a Roundcube DSN. */
    public function dsn(?string $name = null): string
    {
        $connection = config('database.connections.'.($name ?? config('database.default')));

        return match ($connection['driver'] ?? null) {
            'mysql', 'mariadb' => $this->serverDsn('mysql', $connection),
            'pgsql' => $this->serverDsn('pgsql', $connection),
            'sqlite' => 'sqlite:///'.str_replace('\\', '/', (string) $connection['database']).'?mode=0646',
            default => throw new RuntimeException('Roundcube can\'t use the "'.($connection['driver'] ?? '?').'" database driver.'),
        };
    }

    /**
     * @param  array<string, mixed>  $connection
     */
    protected function serverDsn(string $scheme, array $connection): string
    {
        $host = (string) $connection['host'].(filled($connection['port'] ?? null) ? ':'.$connection['port'] : '');

        return $scheme.'://'.rawurlencode((string) $connection['username']).':'.rawurlencode((string) $connection['password'])
            .'@'.$host.'/'.rawurlencode((string) $connection['database']);
    }
}
