<?php

$labels = array();
$labels['buttontitle'] = 'Nachricht archivieren';
$labels['buttontitle_compose'] = 'Nachricht archivieren';
$labels['archived'] = 'Nachricht erfolgreich archiviert';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'Epesi Archiv';
$labels['archivesentfolder'] = 'Epesi Sent Archiv';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>
