<?php

$labels = array();
$labels['buttontitle'] = 'Archiver ce message';
$labels['buttontitle_compose'] = 'Archiver ce message';
$labels['archived'] = 'Message archivé avec success';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'Epesi Archive';
$labels['archivesentfolder'] = 'Epesi Sent Archive';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>
