<?php

$labels = array();
$labels['buttontitle'] = 'Arkivera meddelande';
$labels['buttontitle_compose'] = 'Arkivera meddelande';
$labels['archived'] = 'Meddelandet är arkiverat';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'Epesi Arkiv';
$labels['archivesentfolder'] = 'Epesi Sent Arkiv';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>
