<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	  <meta content="text/html; charset=UTF-8" http-equiv="content-type">
	  <title><?php echo __("EPESI setup"); ?></title>
	  <link href="https://fonts.googleapis.com/css?family=Exo+2:400,700|Titillium+Web:400,700&display=swap" rel="stylesheet"> 
	  <link href="include/setup.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<div id="navbar"><div id="navbar_title">navbar title</div></div>