<?php
defined("_VALID_ACCESS") || die('Direct access forbidden');

$pdb = new PatchesDB();
if ($pdb->was_applied(md5('modules/Utils/RecordBrowser/patches/20140827_search_include.php'))) {
    return;
}

PatchUtil::db_add_column('recordbrowser_table_properties', 'search_include', 'I1 DEFAULT 0');
PatchUtil::db_add_column('recordbrowser_table_properties', 'search_priority', 'I1 DEFAULT 0');
Utils_RecordBrowserCommon::set_search('company',1,2);
Utils_RecordBrowserCommon::set_search('contact',1,2);
Utils_RecordBrowserCommon::set_search('crm_meeting',2,0);
Utils_RecordBrowserCommon::set_search('phonecall',2,0);
Utils_RecordBrowserCommon::set_search('task',2,0);
Utils_RecordBrowserCommon::set_search('crm_assets',2,0);
Utils_RecordBrowserCommon::set_search('rc_mail_threads',2,-1);
Utils_RecordBrowserCommon::set_search('rc_mails',2,-1);
Utils_RecordBrowserCommon::set_search('rc_multiple_emails',2,0);
Utils_RecordBrowserCommon::set_search('custom_projects',1,1);
Utils_RecordBrowserCommon::set_search('custom_personalequipment',2,-2);
Utils_RecordBrowserCommon::set_search('custom_jobsearch',2,0);
Utils_RecordBrowserCommon::set_search('custom_jobsearch_history',2,-1);
Utils_RecordBrowserCommon::set_search('custom_ccn_sales',2,0);
Utils_RecordBrowserCommon::set_search('custom_monthlycost',2,0);
Utils_RecordBrowserCommon::set_search('custom_merlin_licence',2,0);
Utils_RecordBrowserCommon::set_search('custom_merlin_sent',2,-2);
Utils_RecordBrowserCommon::set_search('utils_attachment',1,0);
Utils_RecordBrowserCommon::set_search('premium_listmanager', 2, 0);
Utils_RecordBrowserCommon::set_search('premium_listmanager_element',2,-1);
Utils_RecordBrowserCommon::set_search('premium_warehouse',2,0);
Utils_RecordBrowserCommon::set_search('premium_projects',2,0);
Utils_RecordBrowserCommon::set_search('premium_invoice',2,0);
Utils_RecordBrowserCommon::set_search('premium_invoice_items',2,-1);
Utils_RecordBrowserCommon::set_search('premium_salesopportunity',2,0);
Utils_RecordBrowserCommon::set_search('premium_timesheet',2,-1);
Utils_RecordBrowserCommon::set_search('premium_weblink',2,0);
Utils_RecordBrowserCommon::set_search('premium_vacation',2,-1);
Utils_RecordBrowserCommon::set_search('premium_generalcontractor',1,1);
Utils_RecordBrowserCommon::set_search('premium_campaignmanager_messages',2,0);
Utils_RecordBrowserCommon::set_search('premium_campaignmanager_email_address',2,-2);
Utils_RecordBrowserCommon::set_search('premium_simpleinvoice',2,1);
Utils_RecordBrowserCommon::set_search('premium_simpleinvoice_items',2,0);
Utils_RecordBrowserCommon::set_search('premium_multiple_addresses',1,0);
Utils_RecordBrowserCommon::set_search('custom_equipment',2,0);
Utils_RecordBrowserCommon::set_search('custom_projects_visit',2,0);
Utils_RecordBrowserCommon::set_search('custom_shopequipment',2,0);
Utils_RecordBrowserCommon::set_search('custom_shopequipment_rental',2,-1);
Utils_RecordBrowserCommon::set_search('custom_tickets',2,0);
Utils_RecordBrowserCommon::set_search('custom_salesgoals',2,0);
Utils_RecordBrowserCommon::set_search('custom_changeorders',2,0);
Utils_RecordBrowserCommon::set_search('premium_warehouse_items',2,0);
Utils_RecordBrowserCommon::set_search('premium_warehouse_items_categories',2,0);
Utils_RecordBrowserCommon::set_search('premium_tickets',2,0);
Utils_RecordBrowserCommon::set_search('premium_assets',2,0);
Utils_RecordBrowserCommon::set_search('premium_assets_service',2,0);
Utils_RecordBrowserCommon::set_search('premium_equipment',2,0);
Utils_RecordBrowserCommon::set_search('premium_generalcontractor_visit',2,0);
Utils_RecordBrowserCommon::set_search('premium_shopequipment',2,0);
Utils_RecordBrowserCommon::set_search('premium_shopequipment_rental',2,-1);
Utils_RecordBrowserCommon::set_search('premium_generalcontractor_tickets',2,0);
Utils_RecordBrowserCommon::set_search('premium_salesgoals',2,0);
Utils_RecordBrowserCommon::set_search('premium_changeorders',2,0);
