<?php

$labels = array();
$labels['buttontitle'] = 'Arkivera meddelande';
$labels['buttontitle_compose'] = 'Arkivera meddelande';
$labels['archived'] = 'Meddelandet är arkiverade';
$labels['archived_duplicate'] = 'Redan arkiverade';
$labels['contactnotfound'] = 'Matching contact or company not found';
$labels['archivefolder'] = 'CRM Arkiv';
$labels['archivesentfolder'] = 'CRM Sent Arkiv';
$labels['invalidfolder'] = 'Cannot move to archive from this folder';

?>